# Generated by Django 2.1.3 on 2018-12-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hangman', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_word', models.CharField(max_length=11)),
                ('guess_number', models.IntegerField()),
                ('letters_left', models.CharField(max_length=11)),
            ],
        ),
    ]
