# Generated by Django 2.1.3 on 2018-12-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0003_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='current_letters',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='word',
            name='letters_guessed',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
