# Generated by Django 2.1.3 on 2018-12-02 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0004_auto_20181202_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='current_letters',
            new_name='right_letters_guessed',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='letters_guessed',
            new_name='wrong_letters_guessed',
        ),
    ]
