# Generated by Django 2.1.3 on 2018-12-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0005_auto_20181202_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='wrong_letters_guessed',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
