# Generated by Django 2.1.3 on 2018-12-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0006_auto_20181203_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='letters_left',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
